/* eslint-disable */
const GETbuildingsBuildingIdUnits = [
  { buildingid: 13, name: 'Archer', wood: 25, food: 0, gold: 45, stone: 0, creationtime: 35, description: 'Archer|Ranged unit. Strong vs. units at long range. Weak vs. Skirmishers and units at close range. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, to Crossbowman 125F, 75G (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 1, building: 13 },
  { buildingid: 13, name: 'Hand Cannoneer', wood: 0, food: 45, gold: 50, stone: 0, creationtime: 34, description: 'Hand Cannoneer|Gunpowder unit with powerful attack, but inaccurate at long range. Strong vs. infantry. Weak vs. Elite Skirmishers and archers. Upgrades: armor (Blacksmith); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 2, building: 13 },
  { buildingid: 13, name: 'Elite Skirmisher', wood: 35, food: 25, gold: 0, stone: 0, creationtime: 22, description: 'Elite Skirmisher|Ranged anti-archer unit that cannot attack at close range. Strong vs. archers. Weak vs. units at close range. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, to Imperial Skirmisher 300W, 450G (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 3, building: 13 },
  { buildingid: 13, name: 'Skirmisher', wood: 35, food: 25, gold: 0, stone: 0, creationtime: 22, description: 'Skirmisher|Ranged anti-archer unit that cannot attack at close range. Strong vs. archers. Weak vs. units at close range. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, to Elite Skirmisher 230W, 130G (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 4, building: 13 },
  { buildingid: 13, name: 'Crossbowman', wood: 25, food: 0, gold: 45, stone: 0, creationtime: 27, description: 'Crossbowman|Ranged unit. Strong vs. units at long range. Weak vs. Elite Skirmishers, Mangonels, and units at close range. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, to Arbalester 350F, 300G (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 10, building: 13 },
  { buildingid: 13, name: 'Cavalry Archer', wood: 40, food: 0, gold: 60, stone: 0, creationtime: 34, description: 'Cavalry Archer|Mounted archer. Strong vs. slow units at long range. Weak vs. Elite Skirmishers and units at close range. Upgrades: speed, hit points (Stable); attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, armor, to Heavy Cavalry Archer 900F, 500G (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 15, building: 13 },
  { buildingid: 13, name: 'Slinger', wood: 0, food: 30, gold: 40, stone: 0, creationtime: 25, description: 'Slinger|Inca unique unit. Ranged anti-infantry unit that cannot attack at close range. Strong vs. infantry. Weak vs. archers and cavalry. Upgrades: attack, range, armor (Blacksmith); accuracy (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 28, building: 13 },
  { buildingid: 13, name: 'Heavy Cavalry Archer', wood: 40, food: 0, gold: 60, stone: 0, creationtime: 27, description: 'Heavy Cavalry Archer|Mounted archer. Strong vs. slow units at long range. Weak vs. Elite Skirmishers and units at close range. Upgrades: attack, range, armor (Blacksmith); accuracy, armor (Archery Range); attack, accuracy (University); speed, hit points (Stable); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 50, building: 13 },
  { buildingid: 13, name: 'Arbalester', wood: 25, food: 0, gold: 45, stone: 0, creationtime: 27, description: 'Arbalester|Ranged unit. Strong vs. units at long range. Weak vs. Elite Skirmishers, Onagers, and units at close range. Upgrades: attack, range, armor (Blacksmith); accuracy (Archery Range); attack, accuracy (University); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 51, building: 13 },
  { buildingid: 13, name: 'Genitour', wood: 35, food: 50, gold: 0, stone: 0, creationtime: 25, description: 'Genitour|Mounted skirmisher. Strong vs. archers. Weak vs. units at close range. Trainable by Berbers and their allies. Upgrades: speed, hit points (Stable); attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, armor, to Elite Genitour 500F, 450W (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 114, building: 13 },
  { buildingid: 13, name: 'Elite Genitour', wood: 35, food: 50, gold: 0, stone: 0, creationtime: 23, description: 'Elite Genitour|Mounted skirmisher. Strong vs. archers. Weak vs. units at close range. Trainable by Berbers and their allies. Upgrades: speed, hit points (Stable); attack, range, armor (Blacksmith); attack, accuracy (University); accuracy, armor (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 115, building: 13 },
  { buildingid: 13, name: 'Imperial Skirmisher', wood: 35, food: 25, gold: 0, stone: 0, creationtime: 22, description: 'Imperial Skirmisher|Ranged anti-archer unit that cannot attack at close range. Strong vs. archers. Weak vs. units at close range. Trainable by Vietnamese and their allies. Upgrades: attack, range, armor (Blacksmith); attack, accuracy (University); accuracy (Archery Range); creation speed (Castle); more resistant to Monks (Monastery).', unitid: 133, building: 13 },
];

const GETbuildingsBuildingIdTechs = [
  { buildingid: 13, name: 'Parthian Tactics', wood: 0, food: 200, gold: 250, stone: 0, creationtime: 65, description: 'Parthian Tactics|Cavalry Archers have +1 normal/+2 pierce armor; Cavalry Archers have +4, Unique Mounted Archers +2 attack vs. pikemen.', techid: 86, building: 13 },
  { buildingid: 13, name: 'Thumb Ring', wood: 250, food: 300, gold: 0, stone: 0, creationtime: 45, description: 'Thumb Ring|Archers fire faster and with 100% accuracy.', techid: 87, building: 13 },
];

const GETgatherrates = [
  { hunt: '0.41', berries: '0.31', sheep: '0.33', fish: '0.43', farm: '0.44', wood: '0.39', gold: '0.38', stone: '0.36' },
];
